server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: x-image-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_image
    username: root
    password: 123456


